# Generated by Django 3.2.8 on 2021-10-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
